version: "3.6"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DB_PASS:-root}
    depends_on:
      - db
      - phpmyadmin

  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME:-wordpress}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASS:-root}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:-root}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8180:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD:=${DB_ROOT_PASS:-root}

    depends_on:
      - db

volumes:
  db_data: